### ISSUE TITLE
Help getting started with WebPack Angular

### ISSUE THREAD

**Issue by alexhawkins** [kentcdodds/webpack-angular#2]
Kent, I watched your webpack tutorial via EggHead and then came here. Just curious about the 'Bad Scripts' commit. In your latest  commit, it seems you're no longer using Webpack. You've removed all the require statements, and it seems you're not even using Webpack. Just curious if there is something about the webpack approach you discuss on EggHead that you didn't like. What are the 'bad scripts' you're referring to? Would you no longer recommend this approach?  Or am I missing something completely? I love webpack and was really hoping i would be able to use it for my next Angular project. Your help getting started with webpack/Angular would be much appreciated. Thanks - Alex.  Great videos on EggHead by the way.

**Comment by Ciantic** [comment]
I'm investigating this too, I'm just retiring browserify, and thinking about webpack. It works great with React, but React is not very good for TypeScript. I think Angular 2 is better bet when using TypeScript.

However I really like the way webpack works, you just update your packages with npm and that's it. Quickly looking this example, it is missing webpack.config.js?

Also I wonder if the problem is ES6 import syntax, maybe webpack doesn't support it natively yet?

**update** also, why is there bower.json? Isn't it useless when using webpack?

**Comment by tylerdmace** [comment]
@Ciantic Webpack, with a bit of work, can use `bower_components` as well as `node_modules`. Also, ES6 is fine if you run it through a transpilation loader like `babel`.

**Comment by kentcdodds** [comment]
I need to give you an apology. For some reason, I want watching this repository so I want getting notifications about issues and pull requests. I am so incredibly sorry. Please forgive me. I really feel awful. I hope my unresponsiveness doesn't hinder you contributing more in the future.

As for your specific pull request, I'll give it a closer look soon.

**Comment by kentcdodds** [comment]
Hello everyone! Again, I'm extremely sorry about not being more responsive :-( Here's what happened: https://twitter.com/kentcdodds/status/694552577254432768

As for the topic at hand. I actually don't remember why I made that change at all. Please forgive me for that :-/ It was a long time ago. If I had to guess, it was a mistake while trying to set up the project for a workshop or something...

Let me just clear the air a bit though:
- Webpack is amazing, I still use it for almost everything.
- Bower is dead, don't use it, just use npm
- Babel 6 changed a lot of stuff, but still use it because it's awesome (TypeScript's cool to I guess).
- JSHint is old, upgrade to ESLint.

Sorry again!
